// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP8g2AQQ96QeJB7JyUZwnE1XBCmaW7cHM',
    appId: '1:736403122925:web:f6f77d49f380a23651bae4',
    messagingSenderId: '736403122925',
    projectId: 'pow-71ebd',
    authDomain: 'pow-71ebd.firebaseapp.com',
    storageBucket: 'pow-71ebd.appspot.com',
    measurementId: 'G-V937M86PBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBcKQBqZn43dcSZt0ttsyEP_TsLktNsJE',
    appId: '1:736403122925:android:5fd10de3794f9a8151bae4',
    messagingSenderId: '736403122925',
    projectId: 'pow-71ebd',
    storageBucket: 'pow-71ebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFLEusjVxVlGiTQ4f-2aIlzk85Tu1fwlQ',
    appId: '1:736403122925:ios:58c3c615fe1654f051bae4',
    messagingSenderId: '736403122925',
    projectId: 'pow-71ebd',
    storageBucket: 'pow-71ebd.appspot.com',
    iosBundleId: 'com.example.pow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFLEusjVxVlGiTQ4f-2aIlzk85Tu1fwlQ',
    appId: '1:736403122925:ios:58c3c615fe1654f051bae4',
    messagingSenderId: '736403122925',
    projectId: 'pow-71ebd',
    storageBucket: 'pow-71ebd.appspot.com',
    iosBundleId: 'com.example.pow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP8g2AQQ96QeJB7JyUZwnE1XBCmaW7cHM',
    appId: '1:736403122925:web:140ec55b72ae318351bae4',
    messagingSenderId: '736403122925',
    projectId: 'pow-71ebd',
    authDomain: 'pow-71ebd.firebaseapp.com',
    storageBucket: 'pow-71ebd.appspot.com',
    measurementId: 'G-BYVV9X7L9G',
  );
}
